### ISSUE TITLE
Broken Project?

### ISSUE THREAD

**Issue by mythz** [ServiceStackApps/ReactChatApps#1]
@Layoric I'm not able to rebuild this project after a clean clone, tried in both VS 2013 and VS 2015, looks like it's due to broken CefSharp references.

The project template and README is also a bit out-dated, can you port ReactChat so it's based on the latest React Desktop Template as it should also resolve the broken dependencies issue. I'll start a new [ReactDesktopApps](https://github.com/ServiceStackApps/ReactDesktopApps) and work on updating the README so it reflects the latest layout, features and workflow in the current template. I'll update the docs here as well after I'm done.

**Comment by mythz** [comment]
ok looks like switching to release mode fixes the [broken DEBUG references](https://github.com/ServiceStackApps/ReactChatApps/blob/master/src/ReactChat/ReactChat.AppWinForms/NativeHost.cs#L83) and I also needed to [remove the ServiceStack.Gap targets](https://github.com/ServiceStackApps/ReactChatApps/commit/e8d683f70f8e33697ef50e9f5adc8d2505986230) so AppConsole would build.

But still have an issue with the splash window in AppWinForms not disappearing due to [not being called from JS](https://github.com/ServiceStackApps/ReactChatApps/blob/master/src/ReactChat/ReactChat.AppWinForms/winforms.js). This might be due to not having run the grunt task which must be corrupted since Task Runner Explorer is reporting no tasks found so I don't have anything to run, anyway all these issues should disappear when it's ported to the latest template.

FYI, the way I [upgraded RedisReact](https://github.com/ServiceStackApps/RedisReact/commit/af948b7793c0dfd95ff0c884fc24f121940f13de) was to create a new template then just copy the project files into the new template.

**Comment by mythz** [comment]
Ok the issue with the Grunt task looks like might have something to do with the missing `publish/config.json` and `deploy/appsettings.txt` that didn't come down with the clone. When I added empty place holders for those I was able to run the grunt task manually through the command-line (i.e. not VS.NET's TRX) then the Grunt tasks started to show up.

I was able to make the WinForms App work by [changing the host to 127.0.0.1 and changing default.cshtml to an embedded resource](https://github.com/ServiceStackApps/ReactChatApps/commit/9cf63dbc2000442789e1ede67379079f27c7c261) looks like you [accidentally switched it back in your last commit](https://github.com/ServiceStackApps/ReactChatApps/commit/6d5adfa92baac10a99b2f7615a387277a1aba9c2#diff-73de2e74ea17e47df18ff7092e468157R103).

Would still like this ported to latest template, but it's no longer a priority.

**Comment by Layoric** [comment]
Yeah, I agree porting the application again from a new template would be more consistent and easier to update starting with a fresh instance of the template. I'll review/update doco as I go and try and fix issues as I go.

Ahh crap, not sure why I had it as Content rather than EmbeddedResource, sorry. I'll start with a new template and see how I go. Cheers.
